# Formulário

print('\n------------- Preencha o formulário abaixo -------------')
print('\nInformações Pessoais')
nome = input('Informe seu nome completo: ')
rg = input('Informe seu RG: ')
cpf = input('Informe seu CPF: ')
nascimento = input('Informe sua data de nascimento: ')
sexo = input('Informe seu sexo: ')
nacionalidade = input('Informe sua nacionalidade: ')
escolaridade = input('Informe sua escolaridade: ')
print('\nInforme seu endereço...')
cep = input('Informe seu CEP: ') # 96780-072
rua = input('Rua: ')
numero = input('Nº: ')
bairro = input('Bairro: ')
cidade = input('Cidade: ')
estado = input('Estado: ')
pais = input('País: ')
print('\nDados de Contato')
telefone = input('Informe seu telefone: ')
email = input('Informe seu e-mail: ')

print('\n--------------- Formulário Preenchido ----------------')
print('\nDados Pessoais')
print('Nome: ',nome)
print('RG: ',rg)
print('CPF: ',cpf)
print('Data de Nascimento: ',nascimento)
print('Sexo: ',sexo)
print('Nacionalidade: ',nacionalidade)
print('Escolaridade: ',escolaridade)
print('\nEndereço')
print('CEP: ',cep)
print('Endereço: ',rua)
print('Cidade: ',numero)
print('Estado: ',bairro)
print('País: ',cidade)
print('País: ',estado)
print('País: ',pais)
print('\nDados de Contato')
print('País: ',telefone)
print('País: ',email)
print()